sudo: required
services:
        - docker

before_install:
        - docker build -t codemastering/docker-react -f Dockerfile.dev .

script:
        - docker run codemastering/docker-react npm run test -- -- coverage
